services:
  db:
    image: postgres:14.0
    container_name: collocutor-db
    restart: unless-stopped
    tty: true
    ports:
      - '5432:5432'
    environment:
      - PGHOST=localhost
      - PGDATABASE=training_data
      - PGUSER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - my-db-postgres:/var/lib/postgresql/data

volumes:
  my-db-postgres:
