services:
  db:
    image: postgres:14.0
    container_name: collocutor-db
    restart: unless-stopped
    tty: true
    ports:
      - '5432:5432'
    environment:
      - PGHOST=localhost
      - PGDATABASE=training_data
      - PGUSER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - ./db_data/psql:/var/lib/postgresql/data
  bot:
    container_name: jesus_bot
    tty: true
    depends_on:
      - db
    links:
      - db
    build: .
    env_file:
      - .env
    ports:
      - '3000:3000'
    volumes:
      - .:/app
